### ISSUE TITLE
Add Json deserializer

### ISSUE THREAD

**Issue by Deefoozy** [Deefoozy/MultiThreadedWebSocketServer#2]
To be able to use messaged received from clients it would be nice if there was a json decoder that converts sent Json to an object.
I'd like to use `System.Text.Json.Serialization` for this.

**Comment by tjeerddie** [comment]
hi, could I work on this

**Comment by tjeerddie** [comment]
general json deserializer is not necessary, you can use the function `JObject.Parse(json)` from `Newtonsoft.Json.Linq` to parse it to a dynamic object.

or use `system.Text.Json` to cast it to an object.

**Comment by Deefoozy** [comment]
I would prefer using `System.Text.Json` instead of the `Newtonsoft` package as .net core 3.0 has the sys.text built in.
However it using the built ins it still takes one line. so I don't think it's necessary to write a set of functions for it.
