### ISSUE TITLE
Add .editorconfig to automatically apply correct formatting in most common editors

### ISSUE THREAD

**Issue by LDSpits** [Deefoozy/MultiThreadedWebSocketServer#22]
[VS 2019](https://docs.microsoft.com/en-us/visualstudio/ide/create-portable-custom-editor-options?view=vs-2019) and [Rider](https://www.jetbrains.com/help/rider/Using_EditorConfig.html) have support for .editorconfig files. Which automatically apply and overwrite style settings in the editor. This can decrease the stylistic work that needs to be done as seen in #19 for instance.

The only work that needs to be done is determining the style guide for this project. I would like @Deefoozy 's input for that

**Comment by Deefoozy** [comment]
I'll try to have a basic styleguide ready for tomorrow, It'll be close to the standard .net conventions but slightly different (like the code we have now).

Feel free to leave suggestions of course!
