### ISSUE TITLE
Refactor code to be more efficiënt

### ISSUE THREAD

**Issue by Deefoozy** [Deefoozy/MultiThreadedWebSocketServer#4]
Since this in my first project in C#, I'm certain that the code in this repo is far from perfect/efficiënt.
If you find anything that could be improved, it would be very much appreciated if you leave an issue behind!
Of course code improvements are always welcome if they dont break stuff and are consistent with current code!

**Comment by ocode123** [comment]
I can try do this :)

**Comment by Deefoozy** [comment]
Sure! just keep the code consistent (naming etc) with current code and you should be fine!
